# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dictation index
email: mr1128@york.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  A free add-on for Dragon speech recognition software allowing quick and easy dictation of mathematics and LaTeX. Requires Natlink, python 2.7 and dragonfly.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://wildflame.me" # the base hostname & protocol for your site
# twitter_username: Taffyer
github_username:  mrob95

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
